has_parameters: true

map_file: 'small_maze.txt'

rot_spread: 0.4
vel_spread: 0.7
updates_before_resample: 2
times_to_resample: 1
prob_sigma: 0.0005
maze_xmax: 2.48
maze_ymax: 2.44
ir_positions_1: [0.042,0.022,0.87]
ir_positions_2: [0.02,-0.009,0.0]
ir_positions_3: [0.030,-0.032,-1.05]
ir_positions_4: [-0.031,-0.025,-1.57]
ir_positions_5: [-0.013,0.026,1.57]
ir_positions_6: [-0.09,0.017, 3.14]

known_pos: false
start_x: 0.1
start_y: 0.2
start_theta: 0.0

wheel_radius: 0.05
wheel_base: 0.21

# Kp_left: 7.6
# Ki_left: 2.92
# Kd_left: 0.2

# Kp_right: 8.0
# Ki_right: 1.99
# Kd_right: 0.3

### THE MOTOR CONTROLLER

Kp_left: 7.6
Ki_left: 2.90
Kd_left: 0.2

Kp_right: 8.0
Ki_right: 2.0
Kd_right: 0.3

### THE PATH CONTROLLER

#standing still and rotating
control_Kp_rot_rot: 4.0
control_Ki_rot_rot: 1.0
control_Kd_rot_rot: 0.0

#moving forward and rotating
#was 2.5, 0.5, 0.0
control_Kp_rot: 3.5
control_Ki_rot: 1.0
control_Kd_rot: 0.0

control_Kp_l: 4.0
control_Ki_l: 0.0
control_Kd_l: 0.0

node_vicinity_threshold: 0.045
rotation_threshold: 0.3


