has_parameters: true

map_file: 'small_maze.txt'

rot_spread: 0.3
vel_spread: 0.7
updates_before_resample: 5
times_to_resample: 1
prob_sigma: 0.001
maze_xmax: 2.48
maze_ymax: 2.44
ir_positions_1: [0.042,0.022,0.87]
ir_positions_2: [0.03,-0.009,0.0]
ir_positions_3: [0.030,-0.032,-1.05]
ir_positions_4: [-0.031,-0.025,-1.57]
ir_positions_5: [-0.013,0.026,1.57]
ir_positions_6: [-0.09,0.017, 3.14]

known_pos: true
start_x: 0.68
start_y: 0.22
start_theta: 0.0

wheel_radius: 0.05
wheel_base: 0.21

p_left: 9.0
i_left: 2.0
d_left: 0.05
p_right: 10.0
i_right: 3.0
d_right: 0.05
